# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 433)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=MainWindow)
        self.groupBox_2.setGeometry(QtCore.QRect(13, 81, 451, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.pos_l = QtWidgets.QLabel(parent=self.groupBox_2)
        self.pos_l.setObjectName("pos_l")
        self.horizontalLayout_2.addWidget(self.pos_l)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dist_l = QtWidgets.QLabel(parent=self.groupBox_2)
        self.dist_l.setObjectName("dist_l")
        self.horizontalLayout_2.addWidget(self.dist_l)
        self.groupBox = QtWidgets.QGroupBox(parent=MainWindow)
        self.groupBox.setGeometry(QtCore.QRect(13, 12, 451, 69))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.portlist = QtWidgets.QComboBox(parent=self.groupBox)
        self.portlist.setObjectName("portlist")
        self.horizontalLayout.addWidget(self.portlist)
        self.connect_b = QtWidgets.QPushButton(parent=self.groupBox)
        self.connect_b.setObjectName("connect_b")
        self.horizontalLayout.addWidget(self.connect_b)
        self.disconnect_b = QtWidgets.QPushButton(parent=self.groupBox)
        self.disconnect_b.setObjectName("disconnect_b")
        self.horizontalLayout.addWidget(self.disconnect_b)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=MainWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 159, 441, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Информация"))
        self.label.setText(_translate("MainWindow", "Угол:"))
        self.pos_l.setText(_translate("MainWindow", "Null"))
        self.label_2.setText(_translate("MainWindow", "Расстояние:"))
        self.dist_l.setText(_translate("MainWindow", "Null"))
        self.groupBox.setTitle(_translate("MainWindow", "Подключение"))
        self.connect_b.setText(_translate("MainWindow", "Connect"))
        self.disconnect_b.setText(_translate("MainWindow", "Disconnect"))
